import { InterviewExperience, CompanyStat } from "./community-api";

export const CURATED_INTERVIEWS: InterviewExperience[] = [
  {
    id: "exp_google_2025",
    companyName: "Google",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    roleTitle: "Software Development Engineer - I",
    jobType: "FULL_TIME",
    packageCTC: "32 LPA (22 Base + Stock)",
    location: "Bangalore / Hyderabad",
    driveType: "ON_CAMPUS",
    difficulty: "HARD",
    selectionStatus: "SELECTED",
    graduationYear: 2025,
    summary: "Cracked Google On-Campus drive in Sept 2025. 1 OA round + 3 Technical interviews + 1 Googleyness fit round.",
    tips: "Never jump straight into coding! Explain brute force first, discuss time/space complexities, write modular code, and test with corner cases like empty arrays and integer overflows.",
    preparationResources: "LeetCode Top 150 Interview Questions, NeetCode 150, Striver's SDE Sheet, System Design Primer.",
    isAnonymous: false,
    upvotes: 38,
    createdAt: "2025-10-12T10:00:00.000Z",
    student: {
      id: "usr_senior_alex",
      name: "Alex Johnson",
      role: "ALUMNI",
      batchYear: 2025,
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AlexJohnson",
      department: { code: "CSE", name: "Computer Science & Engineering" },
    },
    university: {
      name: "Apex University of Technology",
      code: "AUT",
    },
    rounds: [
      {
        roundNumber: 1,
        roundName: "Online Assessment (OA)",
        roundType: "Coding",
        duration: "90 mins",
        details: "2 algorithmic problems on HackerEarth platform. Time efficiency was key.",
        questions: [
          "Given a tree with N weighted nodes, find the maximum path sum between any two leaves with an additional parity constraint.",
          "Dynamic Programming: Minimum number of operations to convert string A to B with custom character insertion penalties.",
        ],
      },
      {
        roundNumber: 2,
        roundName: "Technical Round 1 (DSA & Core)",
        roundType: "Technical",
        duration: "45 mins",
        details: "Google Meet + Google Docs. Clean code and reasoning were scrutinized.",
        questions: [
          "Design an LRU Cache with Time-To-Live (TTL) expiration on each key. Required O(1) get and put.",
          "Variation: What happens when two threads call put() concurrently? Discuss lock-free approaches.",
        ],
      },
      {
        roundNumber: 3,
        roundName: "Technical Round 2 (Algorithms & Graphs)",
        roundType: "Technical",
        duration: "45 mins",
        details: "Focused heavily on Graph Traversal and Topological sorting.",
        questions: [
          "Course Schedule II variation with cycle detection and lexicographically smallest order.",
          "Discussion on memory overhead of adjacency matrix vs adjacency list.",
        ],
      },
      {
        roundNumber: 4,
        roundName: "Googleyness & Behavioral",
        roundType: "HR / Culture",
        duration: "30 mins",
        details: "Scenario questions about teamwork, handling constructive criticism, and managing deadlines.",
        questions: [
          "Tell me about a time you disagreed with a team lead on a technical approach.",
          "How do you handle ambiguous requirements when building a software component?",
        ],
      },
    ],
  },
  {
    id: "exp_amazon_2025",
    companyName: "Amazon",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    roleTitle: "Software Development Engineer - I",
    jobType: "FULL_TIME",
    packageCTC: "28.5 LPA (17.5 Base + 7 Signon + RSUs)",
    location: "Hyderabad",
    driveType: "ON_CAMPUS",
    difficulty: "MEDIUM",
    selectionStatus: "SELECTED",
    graduationYear: 2025,
    summary: "Amazon Campus Hiring 2025. 1 OA round + 2 Technical Interviews combining DSA and Leadership Principles.",
    tips: "Amazon evaluates Leadership Principles in every single round! Format every story using STAR (Situation, Task, Action, Result). Know 'Customer Obsession' and 'Deliver Results' inside out.",
    preparationResources: "Amazon LP Guide, Leetcode Amazon Tagged Questions, Cracking the Coding Interview.",
    isAnonymous: false,
    upvotes: 29,
    createdAt: "2025-10-18T14:30:00.000Z",
    student: {
      id: "usr_senior_priya",
      name: "Priya Sharma",
      role: "ALUMNI",
      batchYear: 2025,
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaSharma",
      department: { code: "CSE", name: "Computer Science & Engineering" },
    },
    university: {
      name: "Apex University of Technology",
      code: "AUT",
    },
    rounds: [
      {
        roundNumber: 1,
        roundName: "Online Assessment (OA)",
        roundType: "Coding + Work Simulation",
        duration: "105 mins",
        details: "2 Coding problems + 20 mins Work Style Assessment.",
        questions: [
          "Package delivery truck optimization (0/1 Knapsack variation with maximum weight constraint).",
          "String manipulation: Count pairs of substrings that form valid anagrams.",
        ],
      },
      {
        roundNumber: 2,
        roundName: "Technical Interview 1",
        roundType: "Technical + LP",
        duration: "60 mins",
        details: "20 mins LP questions followed by 40 mins live coding.",
        questions: [
          "LP: Describe a time when you took calculated risk to complete a project on time.",
          "Coding: Binary Tree Vertical Order Traversal using BFS and Column indexing.",
          "Follow-up: How to handle duplicate values occurring at the exact same row and column.",
        ],
      },
      {
        roundNumber: 3,
        roundName: "Technical Interview 2",
        roundType: "Technical + LP",
        duration: "60 mins",
        details: "Heavy focus on OOPS and Data Structure selection.",
        questions: [
          "LP: Tell me about a time you had to dive deep to fix a stubborn bug in production.",
          "Design an Autocomplete Search Suggestion system using Trie with frequency-based top 3 recommendations.",
        ],
      },
    ],
  },
  {
    id: "exp_msft_2025",
    companyName: "Microsoft",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    roleTitle: "Software Engineer",
    jobType: "FULL_TIME",
    packageCTC: "24 LPA",
    location: "Bangalore / Noida",
    driveType: "ON_CAMPUS",
    difficulty: "MEDIUM",
    selectionStatus: "SELECTED",
    graduationYear: 2025,
    summary: "Campus recruitment drive in August 2025. 1 Codility test + 3 rounds of technical and managerial interviews.",
    tips: "Microsoft loves clean, production-level code. They check for null pointers, integer bounds, and code reusability.",
    preparationResources: "LeetCode Microsoft Tagged, Operating System internals by Galvin, DBMS normalization.",
    isAnonymous: false,
    upvotes: 22,
    createdAt: "2025-11-01T09:15:00.000Z",
    student: {
      id: "usr_senior_rahul",
      name: "Rahul Verma",
      role: "ALUMNI",
      batchYear: 2025,
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RahulVerma",
      department: { code: "CSE", name: "Computer Science & Engineering" },
    },
    university: {
      name: "Apex University of Technology",
      code: "AUT",
    },
    rounds: [
      {
        roundNumber: 1,
        roundName: "Codility Online Test",
        roundType: "Coding",
        duration: "90 mins",
        details: "3 coding tasks with strict edge-case validation.",
        questions: [
          "Minimum deletions required to make character frequencies unique.",
          "Traverse a 2D matrix representing connected grid islands with obstacle constraints.",
        ],
      },
      {
        roundNumber: 2,
        roundName: "Technical Round 1",
        roundType: "Technical",
        duration: "45 mins",
        details: "DSA & OS concepts.",
        questions: [
          "Reverse nodes in k-Group in a Linked List in O(1) extra space.",
          "OS: Explain virtual memory, page fault handling, and deadlock prevention.",
        ],
      },
      {
        roundNumber: 3,
        roundName: "Technical Round 2 & Fit",
        roundType: "Technical / Managerial",
        duration: "45 mins",
        details: "Project discussion and low-level design.",
        questions: [
          "Deep dive into project architecture: How does your compiler execute user code safely?",
          "Design a Parking Lot system using Object-Oriented principles.",
        ],
      },
    ],
  },
  {
    id: "exp_tcs_2025",
    companyName: "TCS",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg",
    roleTitle: "Digital Cadre - Systems Engineer",
    jobType: "FULL_TIME",
    packageCTC: "7.5 LPA",
    location: "Pan India",
    driveType: "POOL_CAMPUS",
    difficulty: "EASY",
    selectionStatus: "SELECTED",
    graduationYear: 2025,
    summary: "National Qualifier Test (NQT) followed by Technical + HR Interview. Digital cutoff was cleared easily with good practice.",
    tips: "Practice aptitude, logical reasoning, and basic coding on string/arrays. For technical round, know SQL joins, OOPS, and your final year project thoroughly.",
    preparationResources: "IndiaBix for Aptitude, GeeksforGeeks Top 50 Array Problems, SQL 50 LeetCode.",
    isAnonymous: true,
    upvotes: 18,
    createdAt: "2025-11-15T16:45:00.000Z",
    student: {
      id: "usr_senior_anonymous",
      name: "Senior Scholar",
      role: "STUDENT",
      batchYear: 2025,
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SeniorScholar",
      department: { code: "ECE", name: "Electronics & Communication Engineering" },
    },
    university: {
      name: "Apex University of Technology",
      code: "AUT",
    },
    rounds: [
      {
        roundNumber: 1,
        roundName: "TCS NQT Exam",
        roundType: "Aptitude + Advanced Coding",
        duration: "180 mins",
        details: "Foundational Section (Quant/Verbal/Reasoning) + Advanced Coding.",
        questions: [
          "Rotate an array to the right by K steps in O(N) time and O(1) space.",
          "Calculate minimum cost to connect N ropes using a Min-Heap.",
        ],
      },
      {
        roundNumber: 2,
        roundName: "Technical + HR Interview",
        roundType: "Technical & HR",
        duration: "35 mins",
        details: "Discussion on projects, database indexing, and readiness to relocate.",
        questions: [
          "Difference between Clustered and Non-Clustered index in MySQL.",
          "Explain the four pillars of OOPS with real-world examples.",
        ],
      },
    ],
  },
];

export const CURATED_COMPANIES: CompanyStat[] = [
  {
    companyName: "Google",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    count: 1,
    packages: ["32 LPA (22 Base + Stock)"],
  },
  {
    companyName: "Amazon",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    count: 1,
    packages: ["28.5 LPA (17.5 Base + 7 Signon + RSUs)"],
  },
  {
    companyName: "Microsoft",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    count: 1,
    packages: ["24 LPA"],
  },
  {
    companyName: "TCS",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg",
    count: 1,
    packages: ["7.5 LPA"],
  },
];
